### PR TITLE
Add missing dependency on Try::Tiny

### PR DESCRIPTION
**Pull request by nielslaukens**
On my system, Try::Tiny was not installed and not pulled in as a dependency. I've added it explicitly, so the `perl Build.PL` step will report this.

### CODE REVIEW

**Comment by emarcotte** [comment]
Cool. Good find. Could you just move it into the normal 'require' section, rather than build_require?

**Comment by nielslaukens** [comment]
Hmm, OK. From the name I supposed this was needed for the `Build test`-phase only, not for the runtime.

**Comment by emarcotte** [comment]
Thanks! I merged this by hand cause I mistakenly committed something else before looking at your thing. Thanks for the contribution! I'll probably start a "Contributors" file at some point.

Also, I probably didn't merge it in the sanest possible way, I'm not very good that part git yet.

**Comment by nielslaukens** [comment]
Not that it matters, but you should have been able to have Git do all the heavy lifting, even if you committed something else before you do the merge. I learned a lot from this link: https://help.github.com/articles/merging-a-pull-request

**Pull request closed without merging**
